# This file was generated by GoReleaser. DO NOT EDIT.
cask "constulto" do
  version "0.0.2"

  on_macos do
    on_arm do
      sha256 "4b8b11d9b04b49a7353022dc73344c8f9ba141d9793270b0a71d4e1d2d96decc"
      url "https://github.com/rokoucha/constulto/releases/download/v#{version}/constulto_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f79dc3e4a2a6e668efbfa7fefee37f7b4eb355a63f283c9a6302db79f38c0717"
      url "https://github.com/rokoucha/constulto/releases/download/v#{version}/constulto_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "75fe42846247b80acec4181d1dd3d3db614a1ff94370bc3edaa83ffa72e62903"
      url "https://github.com/rokoucha/constulto/releases/download/v#{version}/constulto_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "35867ce26798e505344fd6e54d87ba0118729b4c0a7bd1007496475afe88c005"
      url "https://github.com/rokoucha/constulto/releases/download/v#{version}/constulto_#{version}_linux_amd64.tar.gz"
    end
  end

  name "constulto"
  desc "Request independent design and implementation reviews from coding agents"
  homepage "https://github.com/rokoucha/constulto"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "constulto"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/constulto"]
    end
  end

  # No zap stanza required
end
