# This file was generated by GoReleaser. DO NOT EDIT.
cask "constulto" do
  version "0.0.1"

  on_macos do
    on_arm do
      sha256 "b3a5ca9bf0fdef82a74d44312fe8028f8d05f091171cfc9b86d69d9f465a5357"
      url "https://github.com/rokoucha/constulto/releases/download/v#{version}/constulto_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "674176f6f65d5e0445c8dd2be3c687fc06ed18a67f09dea2e34a6057a6044108"
      url "https://github.com/rokoucha/constulto/releases/download/v#{version}/constulto_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e53fc3d001eb461d26dcd8d3dad85bf67603b220588276d497b2d4b769d4b5db"
      url "https://github.com/rokoucha/constulto/releases/download/v#{version}/constulto_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "426f09f0fa261138bea52fa8e9948f104681ee63aeab86b3e5ba79ef2c629a3d"
      url "https://github.com/rokoucha/constulto/releases/download/v#{version}/constulto_#{version}_linux_amd64.tar.gz"
    end
  end

  name "constulto"
  desc "Request independent design and implementation reviews from coding agents"
  homepage "https://github.com/rokoucha/constulto"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "constulto"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/constulto"]
    end
  end

  # No zap stanza required
end
